# Generated by Django 2.0.1 on 2018-01-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=400)),
                ('HotelStars', models.CharField(max_length=400)),
                ('Address', models.CharField(max_length=400)),
            ],
        ),
    ]
