# Generated by Django 2.0.1 on 2018-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=400)),
                ('adults', models.CharField(max_length=400)),
                ('child', models.CharField(max_length=400)),
                ('full_name', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=400)),
                ('phone', models.CharField(max_length=400)),
                ('check_in_date', models.CharField(max_length=400)),
                ('check_out_date', models.CharField(max_length=400)),
                ('single_room', models.CharField(max_length=400)),
                ('double_room', models.CharField(max_length=400)),
                ('extra_bed', models.CharField(max_length=400)),
                ('accomodation_type', models.CharField(max_length=400)),
                ('message', models.CharField(max_length=400)),
            ],
        ),
    ]
